extras.txt
lib/python/pcap_listener.py

This resolves some sporadic test failures where packet capturing was used.

pcap_listener.py: Use immediate mode to avoid packet buffering.

---

tests/apps/tests.yaml

This is a follow-up to 9047ff56e8eb323975db5ef51b8278cb7b9ba6d6.

tests.yaml: Remove reference to 'incomplete' directory.

---

tests/channels/pjsip/sdp_offer_answer/incoming/nominal/single-media-stream/audio/packetization/sipp/uac-ptime-accept.xml
tests/channels/pjsip/sdp_offer_answer/incoming/nominal/single-media-stream/audio/packetization/sipp/uac-ptime-decline-endpoint.xml
tests/channels/pjsip/sdp_offer_answer/incoming/nominal/single-media-stream/audio/packetization/sipp/uac-ptime-endpoint.xml

Allows the test to accept maxptime as a variable value. Some providers require a multiple of 20 for the maxptime or fail to complete calls, e.g. Vivo in Brazil. To increase compatibility, only multiples of 20 are now used.
Resolves: #15
This change is required to pass pull request asterisk/asterisk#219

codec_builtin: Use multiples of 20 for maximum_ms

---

tests/rest_api/channels/external_media/off-nominal/test-config.yaml

This test consistently fails on the GitHub CI,
causing every single test run to report failure.
This test is being disabled until such time as
the issue with it is resolved.
Resolves: #28

rest_api: Disable flaky test.

---

tests/channels/pjsip/basic_calls/outgoing/off-nominal/call_canceled/sipp/call_invalid_sdp.xml
tests/channels/pjsip/basic_calls/outgoing/off-nominal/call_canceled/sipp/call_missing_sdp.xml
tests/channels/pjsip/basic_calls/outgoing/off-nominal/call_canceled/test-config.yaml
tests/channels/pjsip/reinvite_after_bye/sipp/reinvite-after-bye.xml
tests/channels/pjsip/rel100/incoming/peer_supported_require/sipp/check_100rel.xml
tests/channels/pjsip/rel100/incoming/peer_supported_used/sipp/check_100rel.xml
tests/channels/pjsip/transfers/blind_transfer/off_nominal/transferer_reinvite/sipp/transferer.xml

pjproject 2.14 introduced some changes that caused some of our tests to
fail. These tests ended up being either incorrect or not flexible enough
to handle them, so they have been updated to now pass with correct
behavior.
There are two changes that we were concerned with. The first was a
change to the on_media_update callback which allowed it to be called in
error scenarios, and another changed the way that PRACK is processed.
This resulted in getting CANCELs during INVITEs with invalid sdp,
getting additional BYEs in scenarios when multiple INVITEs were sent,
(e.g., reinvite_after_bye test), and the order in which we received the
200 for PRACK and 200 for the INVITE swapping the order in which they
arrived. Since all of these are valid scenarios, the tests have been
updated to reflect …

Fix failing tests for pjproject 2.14.

---

tests/channels/pjsip/diversion/diversion_basic/test-config.yaml

The test keeps failing.  Disable until we can research.
References: #33

Disable channels/pjsip/diversion/diversion_basic

---

lib/python/asterisk/config.py

Python 3.12 warns that regex sequences embedded in strings,
like `"\s*"`, need to be double-escaped: `"\\s*"`
Resolves: #36

config.py: Properly escape regex pattern in is_blank_line

---

lib/python/asterisk/config.py
lib/python/asterisk/opensslversion.py
requirements.txt

Fixed a few more regex escaping issues in config.py and in
opensslversion.py.
Replaced cryptography with pyopenssl in requirements.txt because
cryptography doesn't include the OpenSSL module which we use
to get the openssl version.  Tests that had "openssl" as a prereq
have not been running because of this.
Resolves: #40

More regex and requirements fixes

---

tests/channels/pjsip/diversion/diversion_basic/configs/ast1/pjsip.conf
tests/channels/pjsip/diversion/diversion_basic_drop_options/configs/ast1/pjsip.conf
tests/channels/pjsip/diversion/diversion_caller_id/configs/ast1/pjsip.conf
tests/channels/pjsip/diversion/diversion_request/configs/ast1/pjsip.conf
tests/channels/pjsip/diversion/diversion_request_drop_options/configs/ast1/pjsip.conf
tests/channels/pjsip/diversion/diversion_response/configs/ast1/pjsip.conf
tests/channels/pjsip/diversion/diversion_response_181/configs/ast1/pjsip.conf
tests/channels/pjsip/diversion/diversion_response_drop_options/configs/ast1/pjsip.conf
tests/channels/pjsip/diversion/history_info_request/configs/ast1/pjsip.conf
tests/channels/pjsip/diversion/history_info_response_181/configs/ast1/pjsip.conf
tests/channels/pjsip/diversion/no_diversion_response_181/configs/ast1/pjsip.conf

Enable debug to get packet captures
Bind to 127.0.0.1 instead of 0.0.0.0

pjsip/diversion:  Add debugging options

---

tests/apps/dial/dial_progress/configs/ast1/extensions.conf
tests/apps/dial/dial_progress/test-config.yaml
tests/apps/dial/tests.yaml

Add tests to ensure that the progress timeout
for Dial works as intended.

app_dial: Add tests for progress dial time.

---

tests/channels/pjsip/identify/transport/test-config.yaml

Asterisk PR #602 was reverted due to security concerns so this
test must be disabled until that issue is resolved.

pjsip/identify/transport: Disable due to revert of Asterisk change

---

tests/channels/pjsip/dtmf_sdp/dtmf_sdp_negotiation_alice_asym/sipp/alice_opus-amr16-ulaw_opus.xml
tests/channels/pjsip/dtmf_sdp/dtmf_sdp_negotiation_alice_asym/sipp/alice_opus-ulaw_opus.xml
tests/channels/pjsip/dtmf_sdp/dtmf_sdp_negotiation_alice_asym/sipp/alice_ulaw-amr16-opus_opus.xml
tests/channels/pjsip/dtmf_sdp/dtmf_sdp_negotiation_alice_asym/sipp/alice_ulaw-opus_opus.xml
tests/channels/pjsip/dtmf_sdp/dtmf_sdp_negotiation_bob/sipp/bob_wants_opus_only.xml

Change tests to accept RFC 4733/2833 digits at 8K on an endpoint not configured
for 8K codecs.
Fixes: #776

pjsip dtmf_sdp: Modify tests for mismatched digits

---

tests/apps/dial/dial_announcements/configs/ast1/extensions.conf
tests/apps/dial/dial_announcements/test-config.yaml
tests/apps/queues/queue_member_forward/test-config.yaml
tests/apps/senddtmf/test-config.yaml

* apps/senddtmf: Skipped due to asterisk #818
* apps/queues/queue_member_forward: Fixed events and hangup monitor.
* apps/dial/dial_announcements: Removed random wait, added Wait()s
to allow hangups to process and added min-calls: 4.

tests/apps: Various fixes - cert-18.9-only

---

tests/apps/dial/dial_parallel/dial_parallel_answer_cancel/sipp/charlie.xml
tests/apps/dial/dial_parallel/dial_parallel_answer_cancel/test-config.yaml
tests/apps/dial/dial_parallel/dial_parallel_single_busy/sipp/charlie.xml
tests/apps/dial/dial_parallel/dial_parallel_single_busy/test-config.yaml
tests/apps/dial/dial_parallel/dial_parallel_single_congestion/sipp/charlie.xml
tests/apps/dial/dial_parallel/dial_parallel_single_congestion/test-config.yaml
tests/apps/dial/dial_parallel/dial_parallel_single_no_answer/sipp/charlie.xml
tests/apps/dial/dial_parallel/dial_parallel_single_no_answer/test-config.yaml
tests/apps/dial/dial_parallel/dial_parallel_single_unavail/sipp/charlie.xml
tests/apps/dial/dial_parallel/dial_parallel_single_unavail/test-config.yaml

All 5 tests had the same issues...
* The charlie.xml sipp scenario was copied from other scenarios where
it was sending a BYE.  These tests cause charlie to receive a BYE
so the scenario was changed to expect it within 2 seconds and
if not received, send it.
* The cdr-config in test-config.yaml was also copied from earlier
scenarios that only had one PJSIP and one Local channel and was
therefore expecting only two CDRs.  These tests have two PJSIP
channels and one Local channel and therefore 3 CDRs so another
entry was added to the cdr-config section.

tests/apps/dial/dial_parallel: Fix 5 tests

---

tests/apps/confbridge/sfu/nominal/sipp/video_caller_second.xml
tests/apps/confbridge/sfu/nominal/test-config.yaml
tests/funcs/func_evalexten/configs/ast1/extensions.conf
tests/funcs/func_evalexten/test-config.yaml

* func_evalexten: Answer the calls and set min_calls: 24
* confbridge/sfu/nominal: Added delay before second caller hangs up
and added timeouts to sipp scenarios.

More apps fixes

---

tests/apps/dial/preserve_top/test-config.yaml

The middle sipp scenario fails often.
See https://github.com/asterisk/testsuite/issues/60

Disable tests/apps/dial/preserve_top because of frequent failures

---

tests/manager/config/ManagerConfigTest.py
tests/manager/config/restricted/test-config.yaml

The "restricted" test actually needs a file to test with
so we create "/tmp/test.conf" for it.

manager/config/restricted:  Add temporary file to test

---

tests/channels/pjsip/basic_calls/two_parties/nominal/alice_initiated/alice_hangs_up/configs/ast1/extensions.conf
tests/channels/pjsip/basic_calls/two_parties/nominal/alice_initiated/alice_hangs_up/configs/ast1/pjsip.conf
tests/channels/pjsip/basic_calls/two_parties/nominal/alice_initiated/alice_hangs_up/configs/ast2/pjsip.conf
tests/channels/pjsip/basic_calls/two_parties/nominal/alice_initiated/alice_hangs_up/configs/ast3/pjsip.conf
tests/channels/pjsip/basic_calls/two_parties/nominal/alice_initiated/alice_hangs_up/test-config.yaml
tests/channels/pjsip/basic_calls/two_parties/nominal/alice_initiated/bob_hangs_up/configs/ast1/extensions.conf
tests/channels/pjsip/basic_calls/two_parties/nominal/alice_initiated/bob_hangs_up/configs/ast1/pjsip.conf
tests/channels/pjsip/basic_calls/two_parties/nominal/alice_initiated/bob_hangs_up/configs/ast2/pjsip.conf
tests/channels/pjsip/basic_calls/two_parties/nominal/alice_initiated/bob_hangs_up/configs/ast3/pjsip.conf
tests/channels/pjsip/basic_calls/two_parties/nominal/alice_initiated/bob_hangs_up/test-config.yaml
tests/channels/pjsip/basic_calls/two_parties/nominal/alice_initiated/requested_capabilities/configs/ast1/pjsip.conf
tests/channels/pjsip/basic_calls/two_parties/nominal/alice_initiated/requested_capabilities/configs/ast2/pjsip.conf
tests/channels/pjsip/basic_calls/two_parties/nominal/alice_initiated/requested_capabilities/configs/ast3/pjsip.conf

These tests fail with transport "Address already in use" errors
in certain circumstances.  Changing the tests to use a separate
IPv4 address (127.0.0.10, 127.0.0.11, 127.0.0.12) for each asterisk
instance fixes the issue but these tests also did iterations for
IPv6 and IPv6 only allows a single "::1/128" address on the loopback
interface.  Since we have plenty of other tests that test IPv6 and
there was nothing special about these tests that needed IPv6, it's
been removed from them.

pjsip/.../nominal/alice_initiated: Use separate addrs and remove ipv6

---

lib/python/asterisk/astconfigparser.py
lib/python/asterisk/realtime_converter.py
requirements-realtime.txt
setupVenv.sh

* Fix python3 MultiOrderedDict.keys() issue in astconfigparser.py.
* Updated realtime_converter.py to be compatible with SQLAlchemy 2.
* Added requirements-realtime.txt to install SQLAlchemy, alembic and
psycopg2.
* Updated setupVenv.sh to install from requirements-realtime.txt
if the `--realtime` argument was passed in.

Updates for running the testsuite using realtime database

---

tests/apps/dial/dial_progress/test-config.yaml

Resolves an issue with bridging to an undefined context and re-enables the test following an underlying bug with the feature being fixed.

dial_progress: Fix broken progress timeout test.

---

tests/apps/dial/dial_progress/configs/ast1/extensions.conf
tests/apps/dial/dial_progress/test-config.yaml

* Fix originate to extension '0' instead of 's' as in dialplan.
* Eliminate the Fail UserEvent if we continue past the pass dials. Previously, the test suite would initiate shutdown as soon as 2 passes were received, which caused the answer dial channel allocation to fail, leading dialplan execution to continue onwards to stuff it wasn't supposed to execute in a successful test, triggering a failure. To test the same scenario, explicitly continue onwards and check DIALSTATUS for an additional pass, which should prevent us from getting shut down before the test has concluded.

dial_progress: Fix originate and improve test robustness.

---

tests/rest_api/bridges/error/error.py

The recent change to asterisk bridging (asterisk/asterisk#1094) changed
the return code for duplicate bridge creation from 500 (internal error)
to the more proper 409 (conflict).

rest_api/bridges/error: Fix expected return code.

---

tests/manager/action-events-response/test-config.yaml
tests/manager/authlimit/test-config.yaml
tests/manager/authtimeout/test-config.yaml
tests/manager/config/restricted/test-config.yaml

* Added scenarios to the manager/config/restricted test to cover CreateConfig.
* Fixed the spelling of "privileges" in manager/config/restricted.
* Marked manager tests that require Lua as skipped until they can be
rewritten.
* action_events_response
* authlimit
* authtimeout

manager: Add scenarios to the config/restricted test.

---

lib/python/asterisk/asterisk.py
lib/python/asterisk/test_case.py
lib/python/asterisk/test_config.py
runtests.py

A new `--testsuite-config=<yaml_file>` option has been added to runtests.py
that allows different test configurations to be used without having to
swap out the checked-in default `test-config.yaml`.  It can be used
in the following scenarios:
* Realtime tests:  The realtime tests require database connection information
be specified in the top-level test-config.yaml.  Instead of replacing it
with a modified version, you can now create a separate file, say
`test-config-realtime.yaml` and specify it with
`./runtests.py --testsuite-config=./test-config-realtime.yaml ...`
* Using a running asterisk instance:  Sometimes it's handy to run a testsuite
test against a running instance of asterisk. This requires specifying host
information in the top-level test-config.yaml. Assuming the instance is …

Allow an alternate top-level test-config.yaml file to be used.

---

configs/logger.conf

Make two changes to the default logger.conf used for tests, to make it significantly easier to debug failing tests:
* Include ms in log messages, rather than just seconds.
* Include line numbers in log messages, instead of just the filename.

logger.conf: Include ms and line numbers in log files.

---

tests/rest_api/external_interaction/attended_transfer/stasis_bridge_to_stasis_app_ari_only/configs/ast1/extensions.conf
tests/rest_api/external_interaction/attended_transfer/stasis_bridge_to_stasis_app_ari_only/configs/ast1/pjsip.conf
tests/rest_api/external_interaction/attended_transfer/stasis_bridge_to_stasis_app_ari_only/sipp/referee.xml
tests/rest_api/external_interaction/attended_transfer/stasis_bridge_to_stasis_app_ari_only/sipp/referer.xml
tests/rest_api/external_interaction/attended_transfer/stasis_bridge_to_stasis_app_ari_only/test-config.yaml
tests/rest_api/external_interaction/attended_transfer/tests.yaml

Test that a SIP REFER is translated into a ChannelTransfer event when TRANSFERHANDLING=ari-only is set on the channel and that transfer_progress generates the necessary SIP NOTIFY messages.
Be strict on the first ChannelTransfer event being received. Then only check that the transfer state is changing from not being present, to progress and finally answered. When answered delete all the channels and the bridge and the test wull succeed.

pjsip/rest_api: Introduce a test for ChannelTransfer event

---

lib/python/asterisk/realtime_converter.py
tests/manager/bridge_actions/test-config.yaml

First, the realtime converter was modified to use pathlib to create
parent directories for missing files.
Second, the realtime converter was modified to assume 'global' and
'system' section types in pjsip.conf if the optional type identifier
was not set for the 'global' and 'system' sections respectively.
Lastly, the tests/manager/bridge_actions test was marked as
realtime-incompatible.
Fixes: #89

realtime: Address test failures in realtime_converter

---

tests/rest_api/external_interaction/attended_transfer/stasis_bridge_to_stasis_bridge/same_stasis_app_accepted/sipp/referer.xml

There is no way to guarantee that the NOTIFY(s) will not be received before
the BYE can be sent. Sending the BYE immediately does not affect the generated
events vs waiting so changing the xml to match the other tests in this section.

rest_api: fixing NOTIFY race condition

---

tests/rest_api/applications/subscribe-endpoint/nominal/resource/test-config.yaml
tests/rest_api/bridges/softmix_unhold/test-config.yaml

The following tests used stop_test methods that were inconsistent
with similar tests, leading to intermittent race conditions on
test termination that could cause required events to be missed
rest_api/applications/subscribe-endpoint/nominal/resource
rest_api/bridges/softmix_unhold
This change modifies the tests to match similar tests in the same
categories.

rest_api: race conditions on test teardown

---

tests/channels/iax2/hangupcause/test-config.yaml

iax2/hangupcause test unstable.
Appears to be issues with channels not being created on ast2

iax2: skip unstable hangupcause issue
